#!/bin/sh
#
# 'cra-pick' is a wrapper script that uses 'cra' to pick an Arc commit from the
# history. On success, The script prints the ID of the commit to standard
# output, so that it can be used as a parameter for subsequent commands, e.g.
# 'arc show $(cra-pick)'
#
# In order to be able to display the interface and to catch the commit ID
# (easily) at the same time, 'cra' has to be run with the standard and error
# output channels swapped.
#
# All parameters passed to the script will be forwarded to 'cra'.
#


set -e

CONFIG=$(mktemp)
trap "rm -f '$CONFIG'" EXIT

# Prepare config file: source user config, if present
if [ -n "$CRARC_USER" ]; then
	echo "source $CRARC_USER" >> "$CONFIG"
elif [ -f "$HOME/.crarc" ]; then
	echo "source $HOME/.crarc" >> "$CONFIG"
fi

# Bind Enter to print the selected commit ID to error output and exit after
# that.
echo 'bind main <Enter> <sh -c "echo %(commit) >&2"' >> "$CONFIG"


# Run cra with the standard and error output channels swapped.
export CRARC_USER=$CONFIG
stderr=$(cra "$@" 3>&2 2>&1 1>&3 3>&-) || {
	status=$?
	echo "$stderr" >&2
	exit $status
}
commit=$(echo "$stderr" | tail -n1)

# Check return value for valid commit ID
if ! printf '%s' "$commit" | grep -iqE '^[0-9a-f]{40}$'; then
	echo "$stderr" >&2
	exit 1
fi

echo "$commit"
