cra(1)
======
:docext: adoc
:sysconfdir: /etc

NAME
----
cra - text-mode interface for Arc

SYNOPSIS
--------
[verse]
_______________________________________________________________________
cra        [options] [revisions] [--] [paths]
cra log    [options] [revisions] [--] [paths]
cra show   [options] [revisions] [--] [paths]
cra reflog [options] [revisions]
cra blame  [options] [rev] [--] path
cra grep   [options] [pattern]
cra refs   [options]
cra stash  [options]
cra status
cra <      [Arc command output]
_______________________________________________________________________

DESCRIPTION
-----------

Cra is an ncurses-based text-mode interface for arc(1). It functions
mainly as a Arc repository browser, but can also assist in staging
changes for commit at chunk level and act as a pager for output from
various Arc commands.

OPTIONS
-------

Command line options recognized by Cra include all valid arc-log(1) and
arc-diff(1) options, as well as the following subcommands and Cra-specific
options. The first command line parameter not starting with "-" is interpreted
as being either a revision specification or a path and will end the option
parsing. All additional options will be passed to the underlying Arc command.

Note that this means that any arguments to options should be specified
together. For example, run cra -Sfoo instead of cra -S foo, and cra --grep=foo
instead of cra --grep foo, otherwise foo will be interpreted as a revision
rather than an argument.

show::
	Open diff view using the given arc-show(1) options.

blame::
	Show given file annotated by commits.
	Takes zero or more arc-blame(1) options.
	Optionally limited from given revision.

status::
	Start up in status view.

log::
	Start up in log view, displaying arc-log(1) output.

reflog::
	Start up in reflog view.

refs::
	Start up in refs view. All refs are displayed unless limited by using
	one of the '--branches', '--remotes', or '--tags' parameters.

stash::
	Start up in stash view.

grep::
	Open the grep view. Supports the same options as arc-grep(1).

+<number>::
    Show the first view with line <number> visible and selected.

-v, --version::
	Show version and exit.

-h, --help::
	Show help message and exit.

-C <path>::
	Run as if Cra was started in <path> instead of the current working directory.

PAGER MODE
----------

Cra enters pager mode when input is provided via stdin and supports the
following subcommands and options:

--

 - When the 'show' subcommand is specified and the '--stdin' option is given,
   stdin is assumed to be a list of commit IDs and will be forwarded to the diff
   view's underlying arc-show(1) command. For example:

-----------------------------------------------------------------------------
$ arc rev-list --author=vivien HEAD | cra show --stdin
-----------------------------------------------------------------------------

 - When '--stdin' is given, stdin is assumed to be a list of commit IDs
   and will be forwarded to the main view's underlying arc-log(1)
   command. For example:

-----------------------------------------------------------------------------
$ cra --no-walk --stdin < cherry-picks.txt
-----------------------------------------------------------------------------

 - When '--pretty=raw' is given, stdin is assumed to be a "pretty=raw"
   formatted output similar to that of arc-log(1). For example:

-----------------------------------------------------------------------------
$ arc reflog --pretty=raw | cra --pretty=raw
-----------------------------------------------------------------------------

--

When no subcommands nor options are given, the pager view will be used for
displaying the Arc command input given on stdin. The pager view assumes the
input is either from arc-log(1) or arc-diff(1) and will highlight it similar to
the log and diff views. For example:

-----------------------------------------------------------------------------
$ arc log -Schange -p --raw | cra
-----------------------------------------------------------------------------

EXAMPLES
--------

Display the list of commits for the current branch:
-----------------------------------------------------------------------------
$ cra
-----------------------------------------------------------------------------

Display commits from one or more branches:
-----------------------------------------------------------------------------
$ cra test master
-----------------------------------------------------------------------------

Pretend as if all the refs in `refs/` are listed on the command line:
-----------------------------------------------------------------------------
$ cra --all
-----------------------------------------------------------------------------

Display differences between two branches:
-----------------------------------------------------------------------------
$ cra test..master
-----------------------------------------------------------------------------

Display changes for sub-module versions:
-----------------------------------------------------------------------------
$ cra --submodule
-----------------------------------------------------------------------------

Display changes for a single file:
-----------------------------------------------------------------------------
$ cra -- README
-----------------------------------------------------------------------------

Display contents of the README file in a specific revision:
-----------------------------------------------------------------------------
$ cra show cra-0.8:README
-----------------------------------------------------------------------------

Display revisions between two dates for a specific file:
-----------------------------------------------------------------------------
$ cra --after="2004-01-01" --before="2006-05-16" -- README
-----------------------------------------------------------------------------

Blame file with copy detection enabled:
-----------------------------------------------------------------------------
$ cra blame -C README
-----------------------------------------------------------------------------

Display the list of stashes:
-----------------------------------------------------------------------------
$ cra stash
-----------------------------------------------------------------------------

Grep all files for lines containing `DEFINE_ENUM`:
-----------------------------------------------------------------------------
$ cra grep -p DEFINE_ENUM
-----------------------------------------------------------------------------

Show references (branches, remotes and tags):
-----------------------------------------------------------------------------
$ cra refs
-----------------------------------------------------------------------------

Use word diff in the diff view:
-----------------------------------------------------------------------------
$ cra --word-diff=plain
-----------------------------------------------------------------------------

ENVIRONMENT VARIABLES
---------------------

In addition to environment variables used by Arc (e.g. ARC_DIR), Cra defines
the ones below. The command related environment variables have access to the
internal state of Cra via replacement variables, such as `%(commit)` and
`%(blob)`.
ifdef::version[]
See manpage:crarc[5] for a full list.
endif::version[]
ifndef::version[]
See link:crarc.5.{docext}[crarc(5)] for a full list.
endif::version[]

CRARC_USER::
	Path of the user configuration file (defaults to `~/.crarc` or
	`$XDG_CONFIG_HOME/cra/config`).

CRARC_SYSTEM::
	Path of the system wide configuration file (defaults to
	`{sysconfdir}/crarc`). Define to empty string to use built-in
	configuration.

CRA_LS_REMOTE::
	Command for retrieving all repository references. The command
	should output data in the same format as arc-ls-remote(1).

CRA_DIFF_OPTS::
	The diff options to use in the diff view. The diff view uses
	arc-show(1) for formatting and always passes --patch-with-stat.  You
	may also set the `diff-options` setting in the configuration file.

CRA_TRACE::
	Path for trace file where information about Arc commands is logged.

CRA_SCRIPT::
	Path to script that should be executed automatically on startup. If this
	environment variable is defined to the empty string, the script is read
	from stdin. The script is interpreted line-by-line and can contain
	prompt commands and key mappings. Note that the '<' character must be
	encoded as '<LT>' within the script.

	E.g. CRA_SCRIPT=<(echo :set main-view-commit-title-graph = no) cra

CRA_NO_DISPLAY::
	Open Cra without rendering anything to the terminal. This forces Ncurses
	to write to /dev/null. The main use is for automated testing of Cra.

CRA_EDITOR::
	The editor command to use when visiting files. This environment
	variable overrides (in order of precedence) '$ARC_EDITOR',
	'core.editor' configuration, '$VISUAL' and '$EDITOR', so it
	allows using a different editor from the one Arc uses. The
	value is meant to be interpreted by the shell when it is used.

FILES
-----
'$XDG_CONFIG_HOME/cra/config'::
'~/.config/cra/config'::
'~/.crarc'::
	The Cra user configuration file is loaded in the following way. If
	`$XDG_CONFIG_HOME` is set, read user configuration from
	`$XDG_CONFIG_HOME/cra/config`. If `$XDG_CONFIG_HOME` is empty or
	undefined, read user configuration from `~/.config/cra/config` if it
	exists and fall back to `~/.crarc` if it does not exist. See
	manpage:crarc[5] for examples.

'{sysconfdir}/crarc'::
	System wide configuration file.

'$ARC_DIR/config'::
'~/.gitconfig'::
'{sysconfdir}/gitconfig'::
	Arc configuration files. Read on start-up with the help of
	arc-config(1).

'$XDG_DATA_HOME/cra/history'::
'~/.local/share/cra/history'::
'~/.cra_history'::
	When compiled with readline support, Cra writes a persistent command and
	search history. The location of the history file is determined in the
	following way. If `$XDG_DATA_HOME` is set and `$XDG_DATA_HOME/` exists,
	create `$XDG_DATA_HOME/cra/` if needed and store history to
	`$XDG_DATA_HOME/cra/history`. If `$XDG_DATA_HOME` is empty or undefined,
	store history to `~/.local/share/cra/history` if the directory
	`~/.local/share/cra/` exists, and fall back to `~/.cra_history` if it
	does not exist.

BUGS
----

Please visit Cra's https://github.com/themiron/cra[home page] for information
about new releases and how to report bugs or feature requests.

COPYRIGHT
---------
Copyright (c) 2006-2026 Jonas Fonseca <jonas.fonseca@gmail.com>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

SEE ALSO
--------
ifndef::backend-docbook[]
link:crarc.5.{docext}[crarc(5)],
link:manual.{docext}[the Cra manual],
endif::backend-docbook[]
ifdef::backend-docbook[]
manpage:crarc[5],
manpage:cramanual[7],
endif::backend-docbook[]
arc(1)
