#!/bin/sh
#
# Smoke-test commit display against a mounted Arc working tree.

. libtest.sh
. libarc.sh

use_arc_repo

head_id="$(in_work_dir arc info --json |
	sed -n 's/.*"hash":"\([^"]*\)".*/\1/p')"
[ -n "$head_id" ] || die 'Arc did not provide a HEAD hash'

steps ':save-display show.screen'

test_tig show "$head_id"

assert_contains show.screen "commit $head_id"
assert_contains show.screen '[diff]'
assert_equals stderr < /dev/null
